### PR TITLE
Topbar - move react to peerDependencies 

### PR DESCRIPTION
**Pull request by glosie**
In the process of moving our app to React 16, I noticed that topbar was including it's own (incompatible) version of React in the bundle. Declaring it as a peer dependency allows topbar to rely on the consuming app's `react` module  and avoids having multiple versions in the bundle. It seems like this would be desirable, but if there's a better way to handle this I'd love to know.

I'm not _quite_ sure how this works with the lerna monorepo regarding lockfiles and such... let me know if there's something I should do.

### CODE REVIEW

**Comment by chantastic** [comment]
awesome! thanks @glosie.

I've had trouble with peerDependcies in some of our other shared code. So I put it on the "fuck it" list here until one team finally made the effort to upgrade to v16. Congratulations on being that team :)

I'm actively in this code right now. I'll merge this in tomorrow. But we might have to make other updates in your app to account for the PlatformNotifications => PlatformAnnouncements changes.

**Comment by chantastic** [comment]
@glosie I just published pre-release tag `3.0.0-2` with your changes. give it a whirl and let me know how it goes.

**The `PlatformNotifications` components changed dramatically. You'll have to update that part**.

1. Replace [these `ResourcesTopbar` named statements](https://github.com/ministrycentered/resources/blob/master/app/javascript/components/ResourcesTopbar.jsx#L7-L8) with [this one in the demo app](https://github.com/planningcenter/javascript/blob/master/packages/topbar/dev/dev.tsx#L13).
1. Update from the [build your own `PlatformNotifications` in `ResourcesTopbar`](https://github.com/ministrycentered/resources/blob/master/app/javascript/components/ResourcesTopbar.jsx#L123-L136) to the [batteries included version in the demo app](https://github.com/planningcenter/javascript/blob/master/packages/topbar/dev/dev.tsx#L287-L291).

Obviously hit me up if it doesn't go smoothly.

**Comment by glosie** [comment]
👌Smooth as silk. The only other change required was updating `BellIcon` to `BellSymbol`.

Thanks @chantastic 🙇

**Comment by chantastic** [comment]
oooooh. yes. forgot about those. thanks for the reminder.

**Pull request merged**
