### PR TITLE
add csrf token to platform notifcation POST request

### PR DESCRIPTION
**Pull request by bensie**

### CODE REVIEW

**Comment by chantastic** [comment]
@bensie is this something we'll need deployed in apps by a specified date?

**Comment by bensie** [comment]
@chantastic now :)

**Comment by chantastic** [comment]
@bensie updated and published as [@planningcenter/topbar@3.0.0](https://www.npmjs.com/package/@planningcenter/topbar/v/3.0.0).

all apps should be on a pre-release version. so `yarn upgrade @planningcenter/topbar` bring them quickly up to `3.0.0`.

**screensheet of dist/ files**

image

**Comment by bensie** [comment]
perfect thx

**Pull request merged**
